### ISSUE TITLE
FINUFFT API is thread-safe or not?

### ISSUE THREAD

**Issue by penfe** [flatironinstitute/finufft#72] opened 2020-05-19 03:22 UTC
Dear All,

I would like to call the FINUFFT API in multple-threads, that I could process multiple MRI slices with the multiple cpu cores.

But I failed to do it with my C++ code below, could you please let me know if I missed something? Thanks in advance.

~~~C++
void test_finufft()
{
    size_t n_rows = 254, n_cols = 254, n_partitions = 8;
    size_t n_read = 508, n_spokes = 398;
    std::vector<float> x(n_read * n_spokes);
    std::vector<float> y(n_read * n_spokes);
    std::vector<std::complex<float>> img(n_rows * n_cols);
    std::vector<std::complex<float>> ksp(n_read * n_spokes);    
    nufft_opts m_opts;
    finufft_default_opts(&m_opts);

    int ier = finufft2d2(n_read * n_spokes, x.data(), y.data(), ksp.data(), -1, 1e-3
        , n_rows, n_cols, img.data(), m_opts);

    std::cout << "test_finufft: " << ier << std::endl;
}

int main(int argc, char* argv[])
{
    int n_slices = 50;
#pragma omp parallel for num_threads(8)
    for (int i = 0; i < n_slices; i++)
    {
        test_finufft();
    }

    return 0;
}
~~~

**Comment by penfe** [comment] 2020-05-19 03:26
(gdb) r
Starting program: /tmp/test_finufftf/test
[Thread debugging using libthread_db enabled]
[New Thread 0x7ffff7a29700 (LWP 36920)]
[New Thread 0x7ffff7028700 (LWP 36921)]
[New Thread 0x7ffff6627700 (LWP 36922)]
[New Thread 0x7ffff5c26700 (LWP 36923)]
[New Thread 0x7ffff5225700 (LWP 36924)]
[New Thread 0x7ffff4824700 (LWP 36925)]
[New Thread 0x7ffff3e23700 (LWP 36926)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6627700 (LWP 36922)]
0x00007ffff7a4b584 in search0 () from ../fftw3/lib/libfftw3f.so.3
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.212.el6_10.3.x86_64 libgcc-4.4.7-23.el6.x86_64 libgomp-4.4.7-23.el6.x86_64 libstdc++-4.4.7-23.el6.x86_64

**Comment by ahbarnett** [comment] 2020-05-19 03:56
Dear penfe,

I don't understand your code, since test_finufft() should have i as an argument which changes the img.data slice, right?
Assume so, in which case you're doing multiple transforms with the same x,y NU pt locs, but different c and f, right?
There are 2 ways to do this: 1) each thread does a single-threaded FINUFFT call, or 2) a sequence of multithreaded FINUFFT calls.
The latter is easy for you to try without thread issues.
But it's not obvious which wins, because RAM-movement dominates.
Fortunately we already built a tool for you that does method 1 efficiently: finufft2d2many
Look in the docs and please try this out!
Best, Alex

**Comment by penfe** [comment] 2020-05-19 06:08
Dear Alex,

Thanks for your quickly reply.

My problem is the finufft thread-safty, I am not sure the test_finufft routine is thread safe or not.

If I remove "#pragma omp parallel for num_threads(8)" the code works well, the slice recon one by one. But if I enable the OMP to call test_finufft routine in multiple threads, it crash.

~~~C++
void test_finufft(int nj, float* xj, float* yj, std::complex<float>* cj, int ms, int mt, std::complex<float>* fk)
{   
    nufft_opts m_opts;
    finufft_default_opts(&m_opts);

    int ier = finufft2d2(nj, xj, yj, fk, -1, 1e-3, ms, mt, cj, m_opts);
    std::cout << "test_finufft: " << ier << std::endl;
}

int main(int argc, char* argv[])
{
    size_t n_rows = 254, n_cols = 254, n_partitions = 8, n_slices = 5;
    size_t n_read = 508, n_spokes = 398;
    std::vector<float> x(n_read * n_spokes);
    std::vector<float> y(n_read * n_spokes);

    std::vector<std::complex<float>> ksp(n_read * n_spokes * n_slices);
    std::vector<std::complex<float>> img(n_rows * n_cols * n_slices);

#pragma omp parallel for num_threads(8) // it works if I remove this line to disable omp
    for (int i = 0; i < n_slices; i++)
    {
        // Assume so, in which case you're doing multiple transforms with the same x,y NU pt locs, but different c and f, right?
        // YES
        // also I would like to do the single-slice recon work in one thread: MR data load, nufft, post-processing...
        // hopefully the multi-slcies recon perfomance will be much better with multiple-cup-cores
        // 
        // my problem is the finufft thread-safty, I am not sure the test_finufft routine is thread safe or not
        // http://www.fftw.org/fftw3_doc/Thread-safety.html
                
        // I don't understand your code, since test_finufft() should have i as an argument which changes the img.data slice, right?
        // YES
        std::complex<float>* fk = ksp.data() + (i * n_read * n_spokes);
        // load the real MR acquisition data into var 'ksp', I ignored the code here
        // ...
        std::complex<float>* cj = img.data() + (i * n_rows * n_cols);

        test_finufft(n_read * n_spokes, x.data(), y.data(), cj, n_rows, n_cols, fk);

        // more sigle-slice recon code is ignored here
        // ...
    }
    return 0;
}
~~~

**Comment by penfe** [comment] 2020-05-19 07:25
> 
> 
> Dear penfe,
> 
> I don't understand your code, since test_finufft() should have i as an argument which changes the img.data slice, right?
> Assume so, in which case you're doing multiple transforms with the same x,y NU pt locs, but different c and f, right?
> There are 2 ways to do this: 1) each thread does a single-threaded FINUFFT call, or 2) a sequence of multithreaded FINUFFT calls.
> The latter is easy for you to try without thread issues.
> But it's not obvious which wins, because RAM-movement dominates.
> Fortunately we already built a tool for you that does method 1 efficiently: finufft2d2many
> Look in the docs and please try this out!
> Best, Alex

Dear Alex,

Thanks for your quickly reply.

My problem is the finufft thread-safty, I am not sure the test_finufft routine is thread safe or not.

If I remove "#pragma omp parallel for num_threads(8)" the code works well, the slice recon one by one. But if I enable the OMP to call test_finufft routine in multiple threads, it crash.

~~~C++

void test_finufft(int nj, float* xj, float* yj, std::complex<float>* cj, int ms, int mt, std::complex<float>* fk)
{   
    nufft_opts m_opts;
    finufft_default_opts(&m_opts);

    int ier = finufft2d2(nj, xj, yj, fk, -1, 1e-3, ms, mt, cj, m_opts);
    std::cout << "test_finufft: " << ier << std::endl;
}

int main(int argc, char* argv[])
{
    size_t n_rows = 254, n_cols = 254, n_partitions = 8, n_slices = 5;
    size_t n_read = 508, n_spokes = 398;
    std::vector<float> x(n_read * n_spokes);
    std::vector<float> y(n_read * n_spokes);

    std::vector<std::complex<float>> ksp(n_read * n_spokes * n_slices);
    std::vector<std::complex<float>> img(n_rows * n_cols * n_slices);

#pragma omp parallel for num_threads(8) // it works if I remove this line to disable omp
    for (int i = 0; i < n_slices; i++)
    {
        // Assume so, in which case you're doing multiple transforms with the same x,y NU pt locs, but different c and f, right?
        // YES
        // also I would like to do the single-slice recon work in one thread: MR data load, nufft, post-processing...
        // hopefully the multi-slcies recon perfomance will be much better with multiple-cup-cores
        // 
        // my problem is the finufft thread-safty, I am not sure the test_finufft routine is thread safe or not
        // http://www.fftw.org/fftw3_doc/Thread-safety.html
                
        // I don't understand your code, since test_finufft() should have i as an argument which changes the img.data slice, right?
        // YES
        std::complex<float>* fk = ksp.data() + (i * n_read * n_spokes);
        // load the real MR acquisition data into var 'ksp', I ignored the code here
        // ...
        std::complex<float>* cj = img.data() + (i * n_rows * n_cols);

        test_finufft(n_read * n_spokes, x.data(), y.data(), cj, n_rows, n_cols, fk);

        // more sigle-slice recon code is ignored here
        // ...
    }
    return 0;
}
~~~

**Comment by ahbarnett** [comment] 2020-05-19 19:59
Dear penfe,
If you make with OMP=OFF you'll get single-threaded library which should be thread-safe, and you can try your method. However, I would say your "problem" is not thread safety, rather, it is that you would like to compute a stack of 2d2 transforms with same NU pts and changing data. And my previous response explains the best way to do that. I encourage you to try it instead of your method. Alex

**Comment by penfe** [comment] 2020-05-20 01:45
> 
> 
> Dear penfe,
> If you make with OMP=OFF you'll get single-threaded library which should be thread-safe, and you can try your method. However, I would say your "problem" is not thread safety, rather, it is that you would like to compute a stack of 2d2 transforms with same NU pts and changing data. And my previous response explains the best way to do that. I encourage you to try it instead of your method. Alex

1) The code aboved crash with "make lib PREC=SINGLE OMP=OFF", I am not sure it is a thread safety issue with fftw usage.
http://www.fftw.org/fftw3_doc/Thread-safety.html

2) Call test_finufft in parallel with OMP=ON, the code aboved doesn't share the data (memory) between threads except x, y, each thread works with its own cj and fk.
~~~C++
#pragma omp parallel for num_threads(8) 
    for (int i = 0; i < n_slices; i++)
    {
        // ...
        std::complex<float>* fk = ksp.data() + (i * n_read * n_spokes);
        std::complex<float>* cj = img.data() + (i * n_rows * n_cols);
~~~
I also modify the code to stop share x, y offline, but it crash also.

3) finufft2d2many is a nice tool to process multiple-coils data at the same time. But I am working on a MR iterative-recon implementation, 
each slice-level workflow looks like: job A -> job B -> nufft -> job C -> nufft -> job D...., so I am trying to make a thread-safe recon routine in slice level.

**Comment by ahbarnett** [comment] 2020-05-20 17:40
Dear Penfe,

Crashes are *probably* caused by non-thread safe FFTW planning, as you point to.

If thread safety (ie, a desire to run single-threaded FINUFFT in separate threads) is requested by several users, we will address how to plan once and reuse the plan in different threads. Hence I'll reopen the issue.

However, I'll keep pressing you on why you need this, since the fact that you have a sequential need for nufft's is a completely different issue from the multiple-slice multi-thread aspect. I don't see why you can't just synchronize your slice-level workflow so that whenever the "nufft" in the sequence you describe is done, it uses finufft2d2many on all slices together. You'll have to wait for the slowest slice process anyway, so why not just wait at each nufft stage? That would use the machine most effectively (since FFTW gets to make its decisions about how to multithread, rather than you, and they know best!)

Cheers, Alex

**Comment by penfe** [comment] 2020-05-21 00:53
Dear Alex,

Thanks for your comments and suggestion.
 
~~~C++
// My original API design, thread-safe, run single FINUFFT in separate threads
void recon_slice(std::complex<float>* ksp, ..., /*out*/std::complex<float>* img, ...);

// My updated API according to your suggestion, NOT thread-safe, finufft2d2many inside
void recon_slices(int n_slices, std::complex<float>* ksp_set, ..., /*out*/std::complex<float>* img_set, ...);
~~~

Yes the original API lost some performance compared to the finufft2d2many approach, but probably the original API could be integrated into asynchronous MR acquisition and recon pipeline: slice[0] acq ready -> slice[0] recon begin -> slice[1] acq ready -> slice[1] recon begin -> ...

**Comment by ahbarnett** [comment] 2020-05-21 03:07
Ok, sounds like some acquisition-system details here. Let me know if you good performance. We'll be releasing a GPU version soon too (working on interfaces now).

**Comment by ahbarnett** [comment] 2020-08-19 03:43
If you pull the guruInterface_v2 branch, which will soon get released as v2.0 on master, there is a compile flag -DFFTW_PLAN_SAFE that should make FINUFFT thread-safe.  Please try it out!

**Comment by ahbarnett** [comment] 2020-10-06 19:50
v2 is now released and the FFTW_PLAN_SAFE flag is documented. I'll close and hope this fixes the lack of thread safety, until new data comes in.

**Comment by ahbarnett** [comment] 2021-04-19 23:18
Dear @penfe, I have put up a `example/threadsafe1d1.cpp` which will work with FFTW>=3.3.6 if you set `CXXFLAGS+=-DFFTW_PLAN_SAFE`.  Please copy that example, and let me know if it doesn't work for you. Thanks! Alex

**Comment by penfe** [comment] 2021-04-20 04:57
Yes Alex, the threadsafe1d1.cpp works well with the 2 conditions:
* CXXFLAGS+=-DFFTW_PLAN_SAFE 
* opts->nthreads=1;

But my example code with finufftf2d2 below failed:

~~~c++
// this is all you must include for the finufft lib...
#include <finufft.h>

// also used in this example...
#include <vector>
#include <complex>
#include <iostream>
#include <omp.h>
using namespace std;

// g++ -fopenmp test_pf.cpp -I../include ../lib/libfinufft.so -o test_pf -lfftw3 -lfftw3_threads -lm

void test_finufft(nufft_opts* opts)
{
    size_t n_rows = 8, n_cols = 8;
    size_t n_read = 16, n_spokes = 4;
    std::vector<float> x(n_read * n_spokes);
    std::vector<float> y(n_read * n_spokes);
    std::vector<std::complex<float>> img(n_rows * n_cols);
    std::vector<std::complex<float>> ksp(n_read * n_spokes);
    
    int ier = finufftf2d2(n_read * n_spokes, x.data(), y.data(), ksp.data(), -1, 1e-3
        , n_rows, n_cols, img.data(), opts);

    std::cout << "test_finufft: " << ier << std::endl;
}

int main(int argc, char* argv[])
{
  nufft_opts opts;
  finufft_default_opts(&opts);
  opts.nthreads = 1; // this is *crucial* so that each call single-thread

  int n_slices = 50;
#pragma omp parallel for num_threads(4)
    for (int i = 0; i < n_slices; i++)
    {
        test_finufft(&opts);
    }

    return 0;
}
~~~

**Comment by ahbarnett** [comment] 2021-04-20 19:49
Dear penfe,

Ok, now we're getting somewhere! I was able to validate your crash, and gdb shows it is due to fftwf planning.  Unfortunately I have to run on a remote desktop for this: xeon, el7, FFTW 3.3.8, gcc9.3.
And I can also validate @jonas-kr claim that calling fftw once first outside the OMP section is enough to fix the crash.  More precisely I do a very simple finufft1d1 call.
I will write this into docs and make a warm-up call routine.
Here is the working variant of your code:

```
// this is all you must include for the finufft lib...
#include <finufft.h>

// also used in this example...
#include <vector>
#include <complex>
#include <iostream>
#include <omp.h>
using namespace std;

// g++ -fopenmp test_pf.cpp -I../include ../lib/libfinufft.so -o test_pf -lfftw3 -lfftw3_threads -lm -g -Wall

void test_finufft(nufft_opts* opts)
{
    size_t n_rows = 8, n_cols = 8;
    size_t n_read = 16, n_spokes = 4;
    std::vector<float> x(n_read * n_spokes);
    std::vector<float> y(n_read * n_spokes);
    std::vector<std::complex<float>> img(n_rows * n_cols);
    std::vector<std::complex<float>> ksp(n_read * n_spokes);

    int ier = finufftf2d2(n_read * n_spokes, x.data(), y.data(), ksp.data(), -1, 1e-3
        , n_rows, n_cols, img.data(), opts);

    std::cout << "test_finufft: " << ier << "  thread " << omp_get_thread_num() << std::endl;
}

int main(int argc, char* argv[])
{
  nufft_opts opts;
  finufftf_default_opts(&opts);
  opts.nthreads = 1; // this is *crucial* so that each call single-thread

  std::complex<float> c,f;
  float x;
  finufftf1d1(1,&x,&c,1,1e-3,1,&f,NULL);  // *crucial* warmup FFTW outside OMP

  // test_finufft(&opts);  // another way to warm up, but would be more costly

  int n_slices = 50;
#pragma omp parallel for num_threads(4)
    for (int i = 0; i < n_slices; i++)
    {
        test_finufft(&opts);
    }
    return 0;
}
```

Please let me know if that works! This also relates to issues #180 and #183, and I hope can close out all of them. Thanks,  Alex

**Comment by ahbarnett** [comment] 2021-04-20 20:30
Dear penfe, I noticed you were linking to double- not single-prec FFTW. Please fix that in your code. However I found it doesn't prevent a crash. I have also verified that a plain FFTW 1d N=1 transform is enough warm-up. I have no idea why, and find no docs on this online.
I will add some docs on thread-safe use.

**Comment by ahbarnett** [comment] 2021-04-20 23:31
Master 80fd3d3 now has fix for FFTW thread-safety that works, finally, I believe. No additional init commands needed! Please try it. Is it ok if I include an edit of your code as an additional example?

**Comment by penfe** [comment] 2021-04-21 00:56
sure, it's my pleasure.

**Closed** 2021-04-21 01:06 UTC

**Comment by jonas-kr** [comment] 2021-04-21 07:02
Hi Alex, thanks a lot for fixing this issue!
