### ISSUE TITLE
Epsilon Value Incorrect

### ISSUE THREAD

**Issue by thomas-yung** [flatironinstitute/finufft#73] opened 2020-05-19 10:11 UTC
Hello, 

I recently tried to downgrade from the double precision library to the single precision library following the instructions [here](https://finufft.readthedocs.io/en/latest/install.html#custom-library-compilation-options)

However, the value I pass as `eps` (epsilon) to the finufft library call doesn't seem to be the value the library uses, causing an error:
Input: `finufft2d1(nx * nline, x, y, b, +1, 1e-6, npx, npy, F, opts);`
Output: `setup_spreader: error, requested eps (-3.08e-19) is too small (<3e-08)`

For some reason, the hardcoded `1e-6` is being parsed as `-3.08e-19` 
I have tried other values, all of which are parsed incorrectly 

This bug is not present in the double precision library

C++ standard: 11 
Compiler: Clang 10.0.0, g++ 7.5, g++ 8.4 all tried

**Comment by ludvigak** [comment] 2020-05-19 11:52
Most likely the problem is your code. I guess that in single precision `finufft2d1` expects `eps` to be a float, but your hardcoded 1e-6 is interpreted as a double by the compiler (it doesn't know that you mean float).

Casting a double 1e-6 into float gets you -3.08e-19. Consider:

```
    double d = 1e-6;
    float *f = (float*) &d;
    printf("%g\n", *f);
```
outputs `-3.08198e-19`

**Comment by thomas-yung** [comment] 2020-05-19 12:33
Thank you for your help, you may close this issue :)

**Comment by ludvigak** [comment] 2020-05-19 12:50
I can't actually, since I'm not admin on the repo, but you might be able to. Otherwise I think Alex will come by and close it =)

**Closed** 2020-05-19 14:24 UTC
