### ISSUE TITLE
Unable to install for matlab, both on mac and linux

### ISSUE THREAD

**Issue by MartinAverseng** [flatironinstitute/finufft#366] opened 2023-10-18 14:32 UTC
Hi, 

Thanks for this amazing package. I'm trying to install this on two platforms, without success so far. 
On mac: I can't get past the make test -j step. I get almost no error message, simply unable to run. Looking at the make file, it seems homebrew is not at the correct place. From online doc, looks like default prefix for homebrew depends on machine
"/usr/local for macOS on Intel
/opt/homebrew for macOS on Apple Silicon/ARM"
i have tried fiddling with paths in the makefile but without success. 

On linux: make test -j works and no fail. Then make matlab prints "MEX completed successfully". 
However, when running on matlab the check_finufft, I get the following, non-small errors

> 1D: using 1000000 modes...
> 1D type-1: rel err in F[370000] is 0.0866
> 1D type-2: rel err in c[930000] is 1.83e-07
> 1D type-3: rel err in f[240000] is 0.0686
> total 1D time: 2.369 s
> 2D: using 2000*500 modes (total 1000000)...
> 2D type-1: rel err in F[900,-175] is 0.154
> 2D type-2: rel err in c[930000] is 7.45e-07
> 2D type-3: rel err in f[240000] is 0.502
> total 2D time: 3.454 s
> 3D: using 140*140*51 modes (total 999600)...
> 3D type-1: rel err in F[63,-49,8] is 0.09
> 3D type-2: rel err in c[930000] is 1.62e-07
> 3D type-3: rel err in f[240000] is 0.235
> total 3D time: 12.197 s
> 2Dmany: 5 data, using 2000*500 modes (total 1000000)...
> 2Dmany type-1: rel err in F[900,-175,3] is 4.52e-07
> 2Dmany type-2: rel err in c[930000,3] is 1.07e-06
> total 2Dmany time: 3.879 s
> All-dimensions total time: 21.902 s

I also tried to install the previous stable release, same problem. 
fig_accuracy outputs a graph where all blue crosses are  at around 0.1. 

> errs =
> 
>   Columns 1 through 8
> 
>     0.0856    0.0886    0.0902    0.1001    0.0890    0.0915    0.0891    0.0862
> 
>   Columns 9 through 14
> 
>     0.0889    0.0892    0.0906    0.1022    0.0856    0.0844
> 

Thanks for your help!

**Comment by lu1and10** [comment] 2023-10-18 16:16
For Mac, have you tried the `make.inc.macosx_arm64_matlab2022b_beta` to include in makefile?
For Linux, what is the Matlab version and CPU used, I can't reproduce the error on my linux machine.

**Comment by MartinAverseng** [comment] 2023-10-19 06:08
Hi, and thanks for your reply. 

On the Mac front: 

I figured out the issue. I had copied the sources from my ubuntu machine, and was working on them from my mac using Dropbox. 
I deleted everything and cloned finufft directly from my mac. Now make test runs, although I have new issues with make matlab, which I'm trying to figure out, I'll let you know the progress.


On the Linux front: 

Matlab R2018a
FYI, I had to modify the make file to link MEX properly: had to change 
mex -> /usr/local/MATLAB/R2018a/bin/mex

CPU version:
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0 
is this what you need? FYI, gcc is also 11.4.0

When I "make matlab", it says
/usr/local/MATLAB/R2018a/bin/mex matlab/finufft.cpp lib-static/libfinufft.a -Iinclude -largeArrayDims -D_OPENMP -DR2008OO -lfftw3 -lfftw3_omp -lfftw3f -lfftw3f_omp -lm -lgomp -output matlab/finufft
Building with 'g++'.
MEX completed successfully.

FYI, In both cases, I had recently made my own mex files for C++ scripts, and I had to make some changes to the default mex configurations for it to work, maybe I did something wrong there.

**Comment by MartinAverseng** [comment] 2023-10-22 12:23
Update for the Linux non-small errors 
In check_nufft, I noticed that variables fe and f are almost exactly in a ratio of 4. 
That is, once I change all lines like

fprintf('3D type-3: rel err in f[%d] is %.3g\n',k,abs((fe-f(k))/max(f(:))))

into  

fprintf('3D type-3: rel err in f[%d] is %.3g\n',k,abs((fe-0.25*f(k))/max(f(:))))

the errors are all below 1e-6:

1D: using 1000000 modes...
1D type-1: rel err in F[370000] is 3.54e-08
1D type-2: rel err in c[930000] is 1.03e-07
1D type-3: rel err in f[240000] is 1.45e-07
total 1D time: 0.777 s
2D: using 2000*500 modes (total 1000000)...
2D type-1: rel err in F[900,-175] is 1.68e-07
2D type-2: rel err in c[930000] is 8.83e-07
2D type-3: rel err in f[240000] is 1.23e-07
total 2D time: 1.069 s
3D: using 140*140*51 modes (total 999600)...
3D type-1: rel err in F[63,-49,8] is 7.98e-08
3D type-2: rel err in c[930000] is 5.41e-07
3D type-3: rel err in f[240000] is 1.01e-07
total 3D time: 3.386 s
2Dmany: 5 data, using 2000*500 modes (total 1000000)...
2Dmany type-1: rel err in F[900,-175,3] is 4.25e-07
2Dmany type-2: rel err in c[930000,3] is 1.03e-06
total 2Dmany time: 1.541 s
All-dimensions total time: 6.774 s

Any idea where this factor 4 could come from?

**Comment by lu1and10** [comment] 2023-10-23 11:27
> Update for the Linux non-small errors There is a factor 4 going on in finufft**x**d**j** for **x** = 1,2,3 and **j** = 1 or **j** = 3, except in the case of "2D many". Indeed, I obtain small errors in check_finufft and check_finufft_single after the following changes: (in check_finufft, but analogous changes in check_finufft_single):
> 
> **line 28:** `f = finufft1d1(x,c,isign,eps,N,o);` _becomes_ `f = 0.25*finufft1d1(x,c,isign,eps,N,o);` **line 42:** `f = finufft1d3(x,c,isign,eps,N,o);` _becomes_ `f = 0.25*finufft1d3(x,c,isign,eps,N,o);` **line 52:** `f = finufft2d1(x,c,isign,eps,N,o);` _becomes_ `f = 0.25*finufft2d1(x,c,isign,eps,N,o);` **line 69:** `f = finufft2d3(x,c,isign,eps,N,o);` _becomes_ `f = 0.25*finufft2d3(x,c,isign,eps,N,o);` **line 79:** `f = finufft3d1(x,c,isign,eps,N,o);` _becomes_ `f = 0.25*finufft3d1(x,c,isign,eps,N,o);` **line 97:** `f = finufft3d3(x,c,isign,eps,N,o);` _becomes_ `f = 0.25*finufft3d3(x,c,isign,eps,N,o);`
> 
> Then I get this output:
> 
> ```
> > 1D: using 1000000 modes...
> > 1D type-1: rel err in F[370000] is 2.74e-07
> > 1D type-2: rel err in c[930000] is 2.25e-07
> > 1D type-3: rel err in f[240000] is 4.18e-07
> > total 1D time: 0.780 s
> > 2D: using 2000*500 modes (total 1000000)...
> > 2D type-1: rel err in F[900,-175] is 9.05e-07
> > 2D type-2: rel err in c[930000] is 3.89e-07
> > 2D type-3: rel err in f[240000] is 2.18e-07
> > total 2D time: 1.043 s
> > 3D: using 140*140*51 modes (total 999600)...
> > 3D type-1: rel err in F[63,-49,8] is 7.27e-07
> > 3D type-2: rel err in c[930000] is 5.61e-07
> > 3D type-3: rel err in f[240000] is 2.03e-06
> > total 3D time: 3.259 s
> > 2Dmany: 5 data, using 2000*500 modes (total 1000000)...
> > 2Dmany type-1: rel err in F[900,-175,3] is 1.9e-07
> > 2Dmany type-2: rel err in c[930000,3] is 1.36e-06
> > total 2Dmany time: 1.367 s
> > All-dimensions total time: 6.449 s
> ```
> 
> Any idea where this factor 4 could come from?

Thanks for investigating into it, it's interesting that the type 1,3 are miss scaled. You mentioned `make test` passes, just confirm, all you C++ type 1 and type3 tests pass, only Matlab type 1 and type3 tests failed?

And is it only failed for Matlab 2018 in your system, have you tried Matlab newer versions, say 2022 or 2023. I don't have Matlab 2018 installed, I can't reproduce the fails on the newer Matlab versions.

**Comment by MartinAverseng** [comment] 2023-10-24 11:49
Thanks for replying. 
I installed a Matlab R2023b trial version to test and all tests passed. 
I confirm that the make test C++ all pass with small errs/relerrs. 
Only Matlab R2018a type 1 and 3 failed. 
Hence it looks like there's a problem of compatibility with earlier Matlab versions.

**Comment by lu1and10** [comment] 2023-10-24 12:19
Thanks for the update. Another possibility, it may also relate to the matlab 2018b mex supported compilers.

https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/support/sysreq/files/system-requirements-release-2018b-supported-compilers.pdf

In the last page, it mentions gcc 6.3 is supported compiler, gcc 11 may not be compatible to matlab 2018b.

**Comment by ahbarnett** [comment] 2023-11-27 14:47
Since it seemed to be an incompatibility of matlab & gcc versions, closing this. The factor 0.25 error was extremely strange. (PS I have used R2018 with older gcc, eg, 7, in the past and all was fine). Let us know if future issues. Thx!

**Closed as completed by ahbarnett** 2023-11-27 14:47 UTC
